export const QUESTION_PREFIXES = [
  'are',
  'can',
  'does',
  'how',
  'is',
  'what',
  'when',
  'where',
  'which',
  'who',
  'why',
];
export const COMPARISON_OPERATORS = ['and', 'or', 'vs', 'versus'];
export const PREPOSITIONS = ['of', 'for', 'in', 'on', 'at', 'with', 'from', 'by', 'to'];

// https://developers.google.com/custom-search/docs/xml_results_appendices#countryCodes
export const COUNTRIES: { [key: string]: { code: string; id: string } } = {
  'Afghanistan': { code: 'af', id: '2004' },
  'Albania': { code: 'al', id: '2008' },
  'Algeria': { code: 'dz', id: '2012' },
  'American Samoa': { code: 'as', id: '2016' },
  'Andorra': { code: 'ad', id: '2020' },
  'Angola': { code: 'ao', id: '2024' },
  'Antarctica': { code: 'aq', id: '2010' },
  'Antigua and Barbuda': { code: 'ag', id: '2028' },
  'Argentina': { code: 'ar', id: '2032' },
  'Armenia': { code: 'am', id: '2051' },
  'Australia': { code: 'au', id: '2036' },
  'Austria': { code: 'at', id: '2040' },
  'Azerbaijan': { code: 'az', id: '2031' },
  'Bahrain': { code: 'bh', id: '2048' },
  'Bangladesh': { code: 'bd', id: '2050' },
  'Barbados': { code: 'bb', id: '2052' },
  'Belarus': { code: 'by', id: '2112' },
  'Belgium': { code: 'be', id: '2056' },
  'Belize': { code: 'bz', id: '2084' },
  'Benin': { code: 'bj', id: '2204' },
  'Bhutan': { code: 'bt', id: '2064' },
  'Bolivia': { code: 'bo', id: '2068' },
  'Bosnia and Herzegovina': { code: 'ba', id: '2070' },
  'Botswana': { code: 'bw', id: '2072' },
  'Brazil': { code: 'br', id: '2076' },
  'Brunei': { code: 'bn', id: '2096' },
  'Bulgaria': { code: 'bg', id: '2100' },
  'Burkina Faso': { code: 'bf', id: '2854' },
  'Burundi': { code: 'bi', id: '2108' },
  'Cape Verde': { code: 'cv', id: '2132' },
  'Cambodia': { code: 'kh', id: '2116' },
  'Cameroon': { code: 'cm', id: '2120' },
  'Canada': { code: 'ca', id: '2124' },
  'Central African Republic': { code: 'cf', id: '2140' },
  'Chad': { code: 'td', id: '2148' },
  'Chile': { code: 'cl', id: '2152' },
  'China': { code: 'cn', id: '2156' },
  'Christmas Island': { code: 'cx', id: '2162' },
  'Cocos (Keeling) Islands': { code: 'cc', id: '2166' },
  'Colombia': { code: 'co', id: '2170' },
  'Comoros': { code: 'km', id: '2174' },
  'Cook Islands': { code: 'ck', id: '2184' },
  'Costa Rica': { code: 'cr', id: '2188' },
  'Cote d\'Ivoire': { code: 'ci', id: '2384' },
  'Croatia': { code: 'hr', id: '2191' },
  'Cyprus': { code: 'cy', id: '2196' },
  'Czech Republic': { code: 'cz', id: '2203' },
  'Democratic Republic of the Congo': { code: 'cd', id: '2180' },
  'Denmark': { code: 'dk', id: '2208' },
  'Djibouti': { code: 'dj', id: '2262' },
  'Dominica': { code: 'dm', id: '2212' },
  'Dominican Republic': { code: 'do', id: '2214' },
  'Ecuador': { code: 'ec', id: '2218' },
  'Egypt': { code: 'eg', id: '2818' },
  'El Salvador': { code: 'sv', id: '2222' },
  'Equatorial Guinea': { code: 'gq', id: '2226' },
  'Eritrea': { code: 'er', id: '2232' },
  'Estonia': { code: 'ee', id: '2233' },
  'Ethiopia': { code: 'et', id: '2231' },
  'Fiji': { code: 'fj', id: '2242' },
  'Finland': { code: 'fi', id: '2246' },
  'France': { code: 'fr', id: '2250' },
  'French Polynesia': { code: 'pf', id: '2258' },
  'Gabon': { code: 'ga', id: '2266' },
  'Georgia': { code: 'ge', id: '2268' },
  'Germany': { code: 'de', id: '2276' },
  'Ghana': { code: 'gh', id: '2288' },
  'Greece': { code: 'gr', id: '2300' },
  'Grenada': { code: 'gd', id: '2308' },
  'Guam': { code: 'gu', id: '2316' },
  'Guatemala': { code: 'gt', id: '2320' },
  'Guinea': { code: 'gn', id: '2324' },
  'Guinea-Bissau': { code: 'gw', id: '2624' },
  'Guyana': { code: 'gy', id: '2328' },
  'Haiti': { code: 'ht', id: '2332' },
  'Honduras': { code: 'hn', id: '2340' },
  'Hungary': { code: 'hu', id: '2348' },
  'Iceland': { code: 'is', id: '2352' },
  'India': { code: 'in', id: '2356' },
  'Indonesia': { code: 'id', id: '2360' },
  'Iraq': { code: 'iq', id: '2368' },
  'Ireland': { code: 'ie', id: '2372' },
  'Israel': { code: 'il', id: '2376' },
  'Italy': { code: 'it', id: '2380' },
  'Jamaica': { code: 'jm', id: '2388' },
  'Japan': { code: 'jp', id: '2392' },
  'Jordan': { code: 'jo', id: '2400' },
  'Kazakhstan': { code: 'kz', id: '2398' },
  'Kenya': { code: 'ke', id: '2404' },
  'Kiribati': { code: 'ki', id: '2296' },
  'Kuwait': { code: 'kw', id: '2414' },
  'Kyrgyzstan': { code: 'kg', id: '2417' },
  'Laos': { code: 'la', id: '2418' },
  'Latvia': { code: 'lv', id: '2428' },
  'Lebanon': { code: 'lb', id: '2422' },
  'Lesotho': { code: 'ls', id: '2426' },
  'Liberia': { code: 'lr', id: '2430' },
  'Libya': { code: 'ly', id: '2434' },
  'Liechtenstein': { code: 'li', id: '2438' },
  'Lithuania': { code: 'lt', id: '2440' },
  'Luxembourg': { code: 'lu', id: '2442' },
  'Madagascar': { code: 'mg', id: '2450' },
  'Malawi': { code: 'mw', id: '2454' },
  'Malaysia': { code: 'my', id: '2458' },
  'Maldives': { code: 'mv', id: '2462' },
  'Mali': { code: 'ml', id: '2466' },
  'Malta': { code: 'mt', id: '2470' },
  'Marshall Islands': { code: 'mh', id: '2584' },
  'Mauritania': { code: 'mr', id: '2478' },
  'Mauritius': { code: 'mu', id: '2480' },
  'Mexico': { code: 'mx', id: '2484' },
  'Micronesia': { code: 'fm', id: '2583' },
  'Moldova': { code: 'md', id: '2498' },
  'Monaco': { code: 'mc', id: '2492' },
  'Mongolia': { code: 'mn', id: '2496' },
  'Montenegro': { code: 'cs', id: '2499' },
  'Morocco': { code: 'ma', id: '2504' },
  'Mozambique': { code: 'mz', id: '2508' },
  'Myanmar': { code: 'mm', id: '2104' },
  'Namibia': { code: 'na', id: '2516' },
  'Nauru': { code: 'nr', id: '2520' },
  'Nepal': { code: 'np', id: '2524' },
  'Netherlands': { code: 'nl', id: '2528' },
  'New Caledonia': { code: 'nc', id: '2540' },
  'New Zealand': { code: 'nz', id: '2554' },
  'Nicaragua': { code: 'ni', id: '2558' },
  'Niger': { code: 'ne', id: '2562' },
  'Nigeria': { code: 'ng', id: '2566' },
  'Niue': { code: 'nu', id: '2570' },
  'Norfolk Island': { code: 'nf', id: '2574' },
  'North Macedonia': { code: 'mk', id: '2807' },
  'Northern Mariana Islands': { code: 'mp', id: '2580' },
  'Norway': { code: 'no', id: '2578' },
  'Oman': { code: 'om', id: '2512' },
  'Pakistan': { code: 'pk', id: '2586' },
  'Palau': { code: 'pw', id: '2585' },
  'Panama': { code: 'pa', id: '2591' },
  'Papua New Guinea': { code: 'pg', id: '2598' },
  'Paraguay': { code: 'py', id: '2600' },
  'Peru': { code: 'pe', id: '2604' },
  'Philippines': { code: 'ph', id: '2608' },
  'Poland': { code: 'pl', id: '2616' },
  'Portugal': { code: 'pt', id: '2620' },
  'Qatar': { code: 'qa', id: '2634' },
  'Congo': { code: 'cg', id: '2178' },
  'Romania': { code: 'ro', id: '2642' },
  'Rwanda': { code: 'rw', id: '2646' },
  'Saint Kitts and Nevis': { code: 'kn', id: '2659' },
  'Saint Lucia': { code: 'lc', id: '2662' },
  'Saint Vincent and the Grenadines': { code: 'vc', id: '2670' },
  'Samoa': { code: 'ws', id: '2882' },
  'San Marino': { code: 'sm', id: '2674' },
  'Sao Tome and Principe': { code: 'st', id: '2678' },
  'Saudi Arabia': { code: 'sa', id: '2682' },
  'Senegal': { code: 'sn', id: '2686' },
  'Serbia': { code: 'cs', id: '2688' },
  'Seychelles': { code: 'sc', id: '2690' },
  'Sierra Leone': { code: 'sl', id: '2694' },
  'Singapore': { code: 'sg', id: '2702' },
  'Slovakia': { code: 'sk', id: '2703' },
  'Slovenia': { code: 'si', id: '2705' },
  'Solomon Islands': { code: 'sb', id: '2090' },
  'Somalia': { code: 'so', id: '2706' },
  'South Africa': { code: 'za', id: '2710' },
  'South Georgia and the South Sandwich Islands': { code: 'gs', id: '2239' },
  'South Korea': { code: 'kr', id: '2410' },
  'Spain': { code: 'es', id: '2724' },
  'Sri Lanka': { code: 'lk', id: '2144' },
  'Sudan': { code: 'sd', id: '2736' },
  'Suriname': { code: 'sr', id: '2740' },
  'Sweden': { code: 'se', id: '2752' },
  'Switzerland': { code: 'ch', id: '2756' },
  'Tajikistan': { code: 'tj', id: '2762' },
  'Tanzania': { code: 'tz', id: '2834' },
  'Thailand': { code: 'th', id: '2764' },
  'Bahamas': { code: 'bs', id: '2044' },
  'Gambia': { code: 'gm', id: '2270' },
  'Timor-Leste': { code: 'tl', id: '2626' },
  'Togo': { code: 'tg', id: '2768' },
  'Tokelau': { code: 'tk', id: '2772' },
  'Tonga': { code: 'to', id: '2776' },
  'Trinidad and Tobago': { code: 'tt', id: '2780' },
  'Tunisia': { code: 'tn', id: '2788' },
  'Turkey': { code: 'tr', id: '2792' },
  'Turkmenistan': { code: 'tm', id: '2795' },
  'Tuvalu': { code: 'tv', id: '2798' },
  'Uganda': { code: 'ug', id: '2800' },
  'Ukraine': { code: 'ua', id: '2804' },
  'United Arab Emirates': { code: 'ae', id: '2784' },
  'United Kingdom': { code: 'uk', id: '2826' },
  'United States': { code: 'us', id: '2840' },
  'United States Minor Outlying Islands': { code: 'um', id: '2581' },
  'Uruguay': { code: 'uy', id: '2858' },
  'Uzbekistan': { code: 'uz', id: '2860' },
  'Vanuatu': { code: 'vu', id: '2548' },
  'Vatican City': { code: 'va', id: '2336' },
  'Venezuela': { code: 've', id: '2862' },
  'Vietnam': { code: 'vn', id: '2704' },
  'Wallis and Futuna': { code: 'wf', id: '2876' },
  'Yemen': { code: 'ye', id: '2887' },
  'Zambia': { code: 'zm', id: '2894' },
  'Zimbabwe': { code: 'zw', id: '2716' },
};
